--- #YAML:1.0
name:                    Config-Perl-V
version:                 0.13
abstract:                Structured data retreival of perl -V output
license:                 perl
author:              
    - H.Merijn Brand <h.m.brand@xs4all.nl>
generated_by:            Author
distribution_type:       module
provides:
    Config::Perl::V:
        file:            V.pm
        version:         0.13
requires:     
    perl:                5.006
    Config:              0
recommends:
    perl:                5.014001
configure_requires:
    ExtUtils::MakeMaker: 0
build_requires:
    perl:                5.006
test_requires:
    Test::Harness:       0
    Test::More:          0
    Test::NoWarnings:    0
resources:
    license:             http://dev.perl.org/licenses/
    repository:          http://repo.or.cz/w/Config-Perl-V.git
meta-spec:
    version:             1.4
    url:                 http://module-build.sourceforge.net/META-spec-v1.4.html
