--- 
abstract: Structured data retrieval of perl -V output
author: 
  - H.Merijn Brand <h.m.brand@xs4all.nl>
build_requires: 
  perl: '5.006'
configure_requires: 
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: Author, CPAN::Meta::Converter version 2.130880
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Config-Perl-V
provides: 
  Config::Perl::V: 
    file: V.pm
    version: '0.18'
recommends: 
  perl: '5.016003'
requires: 
  Config: 0
  Test::More: 0
  Test::NoWarnings: 0
  perl: '5.006'
resources: 
  license: http://dev.perl.org/licenses/
  repository: http://repo.or.cz/r/Config-Perl-V.git
version: '0.18'
